### ISSUE TITLE
Wilcoxon in Level-2 Statistics

### ISSUE THREAD

**Issue by quentinmoreau** [treder/MVPA-Light#10]
Hello and thank for your great toolbox,

I am having issues in running the mv_statistics  within subjects using 'wilcoxon' instead of 'ttest' in cfg.statistics. My data is the output of mv_classify_across_time in several subjects 

In the function mv_statistics, the line 522 was commented:
%             case 'wilcoxon', [~,~,sts] = signrank(cperf); 

but even when uncommented, there is an error:
SIGNRANK requires vector rather than matrix data.

Any help would be gladly appreciated, 

Best
QM

**Comment by treder** [comment]
Hi Quentin, thank you for your feedback. Wilcoxon was properly implemented yet ... it should work now, can you update and try again?

**Comment by quentinmoreau** [comment]
Dear Matthias, it works great now! thank you for your quick answer and updating !

Best, Quentin
