### ISSUE TITLE
feature request for time-resolved mvpa

### ISSUE THREAD

**Issue by schoffelen** [treder/MVPA-Light#11]
Dear Matthias (@treder) great to see your paper in print! In the context of some collaborative project I was looking into ft_statistics_mvpa and noticed that the documentation is a little bit out of sync with respect to the current version of your code on github (e.g. the preprocess functionality in mvpa-light seems to postdate the current version of ft_statistics_mvpa, and things like upsampling need to be specified (and thus documented) differently. It could also be that the tutorial on the website needs some minor tweaks, but I haven't checked this yet. I will open an issue about this on the fieldtrip github repo, it doesn't have high priority, but it would be good to address this at some point.

I was wondering about a feature request (provided that I sufficiently thoroughly checked your codebase and indeed correctly concluded that this is so far not possible), which relates to doing a sliding timewindow type of time-resolved mvpa, i.e. use as features a bunch of channels/source locations + some time points. 

For me it would be relatively easy to support this from the fieldtrip end, but it might be a cleaner functionality if this were to be supported by the lower level code. I'd be happy to make a PR for this. Let me know what you think.

BW, JM

**Comment by schoffelen** [comment]
OK, I think that my requested feature is actually covered by example6 right?

**Comment by treder** [comment]
Thanks @schoffelen ! Glad it's out, I had focused my research time on the paper and the toolbox and there's now a backlog of changes that need to be made, especially the examples and the Fieldtrip integration. I've streamlined the toolbox, I think it's now more consistent and extendable (the .preprocess field is general purpose) but that's at the expense of download compatibility, which we can catch the way you propose. 

Btw your timing is good, I'll be giving a little MVPA-with-FieldTrip workshop at CUBRIB end of July, so I wanted to rework the Fieldtrip integration and the tutorial this month, as well as creating a new set of examples within MVPA-Light.

Regarding your 2nd post, in principle the searchlight can be defined arbitrarily (across time/frequency/channels/sources).

Regarding the FT integration/tutorial, I guess it's better to continue in the fieldtrip thread.

**Comment by schoffelen** [comment]
good stuff! I am just now also catching up on reading MVPA-light, and it seems that mv_classify is much more general purpose than the mv_classify_across_time etc. I think that eventually it makes sense to be able to tap into mv_classify right away at the level of ft_statistics_mvpa, would you agree? I don't mind giving this a shot.

**Comment by treder** [comment]
Yes indeed. There's an advantage though of using the special purpose functions (mv_classify_across_time and mv_classify_timextime) when possible because they're faster, that's why I kept them in. Feel free to give it a go, thanks.

**Comment by gdemarchi** [comment]
... and, as a side note, mv_classify_timextime(cfg, X, clabel, X2, clabel2) is the only one that yet supports training on one dataset, and testing on a different one. Doing it straight from ft_statistics_mvpa would be the ideal solution, but _please_ don't think of removing it, for us mere mortals doing cross decoding :)

**Comment by schoffelen** [comment]
sure thing, and thanks for letting me know.

**Comment by treder** [comment]
@gdemarchi cross-decoding should ideally be included in mv_classify as well, but it might get ugly code-wise so I've postponed this for the future :D
