### ISSUE TITLE
Error in mv_plot_result

### ISSUE THREAD

**Issue by Sanjeevnara** [treder/MVPA-Light#22]
Hi Matthias, 

I am testing the new examples and i would appreciate them. The first example getting_started_with_classification.m starts from very basics and introduces the functionality of toolbox very well. While running mv_plot_result function, it pops up an error. 

Error using matlab.ui.Figure/set
There is no AutoUpdate property on the Legend class.

Error in mv_plot_result (line 64)
    set(gcf,'defaultLegendAutoUpdate','off');

I am testing the last updated version on github with MATLAB 2014B. My guess is that this Autoupdate functionality was introduced in later MATLAB versions. If i comment line 64 in the mv_plot_result function, it works pretty fine for me. Would you like to remove this line or adding a quick conditional statement to bypass this line of code if the version of MATLAB is below any specified version. 

Thanks 

Best regards 
Sanjeev

**Comment by treder** [comment]
Thanks Sanjeev. MATLAB changes so much across versions this is always a worry. The AutoUpdate option should now only be set if it's available, can you pull again and see whether it works for you now?

**Comment by Sanjeevnara** [comment]
Hi Matthias, 

The issue is resolved now. 

Thanks :)
