### ISSUE TITLE
About Installing the Toolbox in MATLAB 

### ISSUE THREAD

**Issue by batiyilmaz** [treder/MVPA-Light#25]
Dear Matthias Treder,

I've been trying to install the toolbox for days, however, although I've tried everything and followed each step in the instructions, I'm still getting these errors in MATLAB. I'm trying to use the toolbox integrated with FieldTrip:

"Error using ft_hastoolbox
the MVPA-LIGHT toolbox is not installed, see https://github.com/treder/MVPA-Light

Error in ft_statistics_mvpa (line 166)
ft_hastoolbox('mvpa-light', 1);"

Can you please help me with resolving this issue? I'm a Mac user and my MATLAB version is R2022a.

Thank you for your time.

**Comment by treder** [comment]
Hi Bati, this should not happen. I supposed you made sure that the startup folder is in your Matlab path? An easy way to check this is to type `startup_MVPA_Light` in the MATLAB console and press enter. If it executes OK pls double check that the commands are ok for instance by testing code from one of the example scripts. If this works too I suspect that the error is on the Fieldtrip side.

**Comment by batiyilmaz** [comment]
Hi Matthias, thank you for your reply. I made sure that the startup folder is in my MATLAB path and I run startup_MVPA_Light in the console and it worked so now I also suspect that the error is on the FieldTrip side, should I let them know about this?

**Comment by treder** [comment]
Could you double check the according lines in `ft_statistics_mvpa`? I don't have FieldTrip installed on this computer so cannot help with this unfortunately. The FieldTrip team is usually very diligent with their code so maybe you can try to identify the source of the problem first before raising an issue?
With this I'm closing the issue - hope you can resolve it.
