### ISSUE TITLE
About Performing Group-Level Classsification 

### ISSUE THREAD

**Issue by batiyilmaz** [treder/MVPA-Light#26]
Dear @treder,

After I've checked the paper of the toolbox, I've been searching for ways and tutorials to perform group-level analyses for multiple subject data with FieldTrip struct. I wanted ask where should I refer for such information?

Thank you in advance.

**Comment by treder** [comment]
Hi Bati, did the [MVPA-Light tutorials](https://github.com/treder/MVPA-Light/tree/master/examples) (especially the one on stats) not answer your questions? Alternatively, you can also try doing the stats directly in FieldTrip. The MVPA-Light stats code is not fully integrated and tested via FieldTrip, so if you want to use any of the MVPA-Light stats you might be better off using the toolbox directly.

**Comment by treder** [comment]
I'm assuming the issue is solved. Feel free to reopen if necessary.
