### ISSUE TITLE
time*time plot multiclass classification

### ISSUE THREAD

**Issue by nastarandarjani** [treder/MVPA-Light#27]
Hello, I run mvpa_light for an 8 classes dataset with muticlass_lda and F1 score metric. After that, I run mv_plot_result(result, time, time) but I got this error:

Index in position 2 exceeds array bounds (must not exceed 8).

Error in mv_plot_2D (line 149)
            imagesc(x, y, squeeze(dat(ysel,xsel,axnum)));

Error in mv_plot_result (line 230)
                    h.ax(mm) = mv_plot_2D(cfg,
                    squeeze (permute(perf(:,:,ix), [p.plot_dimensions,
                    setdiff(1:3, p.plot_dimensions)])));

Could you please help me to plot the result?

**Comment by treder** [comment]
Hi, for 8 classes you get 8 different F1 values. You cannot plot them in a single time x time plot. 

As a sanity check, can you use 'accuracy' as a metric instead and see whether it works?
If you want to have 8 separate plots with F1 values you might have to separate the results by hand, as I think there's nothing in the code right now that would do that.
