### ISSUE TITLE
How can I plot RDMs?

### ISSUE THREAD

**Issue by nastarandarjani** [treder/MVPA-Light#32]
Hi,
Is there an example of implemented representational dissimilarity matrices and Representational Similarity Analysis?
If not, could you please help me to figure it out and plot it?
I saved raw classifier outputs but I don't have original labels to compute confusion matrix.

**Comment by treder** [comment]
There's already a good toolbox for RSA: https://www.mrc-cbu.cam.ac.uk/methods-and-resources/toolboxes/

There is no separate code for RSA in MVPA-Light. I could consider supporting it in the future but there haven't been any such plans at the moment.
