### ISSUE TITLE
Undefined function or variable 'mv_get_classifier_param'

### ISSUE THREAD

**Issue by pinchunc** [treder/MVPA-Light#34]
Hello, I was trying to run the function 'mv_get_classifier_param', but it's not in the 'utils' folder anymore. Was it replaced by another function?

**Comment by treder** [comment]
Hi @pinchunc  the function was replaced by `mv_get_hyperparameter.m` a while ago. Have you been using an old version of the toolbox perhaps?

**Comment by pinchunc** [comment]
Yes! Okay I found the mv_get_hyperparameter. Thanks a lot!
