### ISSUE TITLE
Typo in mv_plot_topography

### ISSUE THREAD

**Issue by MahHoss** [treder/MVPA-Light#4]
Hi.

I think line 73 in mv_plot_topography should be:
cfg.mark_chans = repmat(cfg.mark_chans(:),[1 P]);

Originally, it was:
cfg.mark_chans = repmeat(cfg.mark_chans(:),[1 P]);

I might be wrong, as it worked for me the way it was with the same cfg variable, but then it stopped working and told me 'Unrecognized function or variable 'repmeat'.', bit weird.

Best wishes.

**Comment by treder** [comment]
funny I don't know how this happened, must have been after that pulled pork  ;-) 
Anyways, many thanks I fixed it!
