### ISSUE TITLE
Error in getting_started_with_classification.m (EXERCISE 11)

### ISSUE THREAD

**Issue by glicalzi** [treder/MVPA-Light#41]
Hello Matthias,

When I try to run exercise 11 (searchlight analysis across both electrodes and time points) using the data you provided, I get the following error:

Error using reshape
Number of elements must not change. Use [] as one of the size inputs to automatically calculate the
appropriate size for that dimension.

Error in squeeze1 (line 12)
X = reshape(X, sz);

Error in mv_classify (line 395)
                    Xtest_ix = squeeze1(Xtest(sample_skip{:}, ix_nb{:}, feature_skip{:}));

Do you have any suggestions on how to fix this issue?

Thank you!

**Comment by treder** [comment]
Hi @glicalzi , there was a little bug in the `squeeze1` function which was exposed by the example. It should be fixed now, can you please pull the repo and check whether it works now?
