### ISSUE TITLE
Multivariate Noise Normalization (MNN)

### ISSUE THREAD

**Issue by ClairePleche** [treder/MVPA-Light#43]
Hello,

I am wondering if there is any way to do MNN in MVPA-Light by specifying the cfg.preprocess?  

Thanks!

Claire

**Comment by treder** [comment]
Hi! 
Not right now. I'm just vaguely familiar with the approach, can you share a link to the standard reference paper (that has the equations). Is there some code as well?

**Comment by ClairePleche** [comment]
Hello,
Thank you for your answer !
Here is a paper using MNN on MEG data with equations: https://www.sciencedirect.com/science/article/pii/S1053811918301411?via%3Dihub

The code that they provide in the paper doesn't include the MNN.

**Comment by treder** [comment]
It took a while but I have an implementation ready now! The code is in a separate branch called `MMN`: https://github.com/treder/MVPA-Light/tree/MMN

To get started, you can use example 9 in this file: 
https://github.com/treder/MVPA-Light/blob/MMN/examples/understanding_spatial_filters.m

Before I merge it into the main branch it would be brilliant if you would be able to provide some feedback on whether it produces the expected result on your side. Thanks!

**Comment by treder** [comment]
The branch has now been merged into the main branch

**Comment by ClairePleche** [comment]
Thank you for the implementation !! I will test it out.
