### ISSUE TITLE
bug: train_logreg L2 weights for nested cross-validation

### ISSUE THREAD

**Issue by aranas** [treder/MVPA-Light#7]
When running the logistic regression with nested cross-validation to find optimal lambda (cfg.mvpa.param.lambda = 'auto') an error occurs because the weights are not split according to inner folds: 

Matrix dimensions must agree.

Error in train_logreg/lr_gradient_and_hessian_tanh_L2 (line 433)
        g = ((cfg.weights .* sigma)' * YX)'/N - sumyxN + lambda * w;

**Comment by treder** [comment]
fixed - this bug slipped in when I added the weights a while ago, thanks for pointing out.
